name: Test GitHub Actions

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: cat-vs-rat-game-linux
            asset_name: cat-vs-rat-game-linux
          # - os: windows-latest
          #   artifact_name: cat-vs-rat-game-windows
          #   asset_name: cat-vs-rat-game-windows.exe
          - os: macos-latest
            artifact_name: cat-vs-rat-game-macos
            asset_name: cat-vs-rat-game-macos    

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Hello
        run: |
          echo "1st Hello from GitHub Actions!"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Triggered by: ${{ github.actor }}"
          echo "Current date:"
          date

      - name: List files
        run: ls -la

      - name: Success
        run: echo "✅ Workflow completed successfully!"
